[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

